blank_issues_enabled: false
contact_links:
  - name: I have a question
    url: https://github.com/lyarenei/jellyfin-plugin-listenbrainz/discussions/categories/q-a
    about: Have a question about the plugin? Ask here.
  - name: Other
    url: https://github.com/lyarenei/jellyfin-plugin-listenbrainz/discussions/categories/general
    about: Have something which does not fit in any category? Post it here.
